# name
name: Update Plugins

on:
  workflow_dispatch:
  schedule:
    - cron:  '10 3 * * *'

# permissions, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions and https://docs.github.com/en/rest/overview/permissions-required-for-github-apps
permissions:
  actions: read # detection of GitHub Actions environment
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

# cancel in progress when a new run starts
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# jobs
jobs:
  UpdatePlugins:
    runs-on: ubuntu-22.04 # https://github.com/actions/runner-images
    timeout-minutes: 60 # the full plugin update process runs about 20 minutes
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: false
          egress-policy: block
          allowed-endpoints: >-
            github.com:443
            api.github.com:443
            codeload.github.com:443
            raw.githubusercontent.com:443
            objects.githubusercontent.com:443
            plugins.jetbrains.com:443
            downloads.marketplace.jetbrains.com:443
            cache.nixos.org:443
            auth.docker.io:443
            registry-1.docker.io:443
            production.cloudflare.docker.com:443
            channels.nixos.org:443
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@8cdf194da984e4f12b2f8c36d1fa107c1dd67f5c # v11
        with:
          kvm: false
          diagnostic-endpoint: "" # opt-out of telemetry
          source-url: "https://github.com/DeterminateSystems/nix-installer/releases/download/v0.19.0/nix-installer-x86_64-linux"
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Git Config
        run: |
          git config --global user.name "Nix JetBrains Plugin Update Bot"
          git config --global user.email "bot.nix-jetbrains-plugins@philippheuer.me"
      - name: Update Plugins
        run: |
          set +e

          # make scripts executable
          chmod +x scripts/*.sh scripts/*.py

          # update flake.lock
          ./scripts/update-flake.sh

          # update ide versions
          ./scripts/update-ide-versions.py

          # update plugins
          ./scripts/update-plugins.py
      - name: Commit and Push
        run: |
          set -e

          # check if data/cache/plugins-latest.json has changed
          if ! git diff --exit-code --quiet data/cache/plugins-latest.json; then
            git add data/*
            git add flake.lock
            git commit -m "feat: update plugins - $(date +'%Y-%m-%dT%H:%M:%S')"
            git push
          else
            echo "No changes in data/cache/plugins-latest.json. Exiting without committing."
          fi
